### ISSUE TITLE
Integrate Jasmine 2.0 and RequireJS in a better way than currently MacysUI does

### ISSUE THREAD

**Issue by tiagorg** [brendajin/marionette-ref-impl#11]
I feel like the way we do is way too much hacky, like having to use setTimeout() everytime on beforeEach.

I want to spike for a more solid approach.

**Comment by tiagorg** [comment]
https://github.com/brendajin/marionette-ref-impl/commit/0f08451156944e1eec5dfd3cb835011407b37fb8

**Comment by joseph-jja** [comment]
I don't think we need to do the setTimout() in the before each, jasmine 1.x has a way to do this that we are not using.  It uses the waits().  So if you are seeing setTimeout then the test is not being done correctly.

**Comment by tiagorg** [comment]
with Jasmine 2.0 there is an even better approach than using ```waits()```, they have a ```done``` callback: this new approach is described at [Upgrading Jasmine - Asynchronous Specs](http://jasmine.github.io/2.1/upgrading.html#section-Asynchronous_Specs)

However my approach here is to require the module outside of the ```describe``` and then we would need no async feature at all :)

Like this: https://github.com/brendajin/marionette-ref-impl/blob/0f08451156944e1eec5dfd3cb835011407b37fb8/test/base/application.spec.js

**Comment by joseph-jja** [comment]
Same thing, different name.  Grunt actually does async with the done() and it can be problematic.

**Comment by tiagorg** [comment]
The advantage of using ```done``` is that if we have more than 1 callback they don't have to be nested, but they would be flattened instead by doing one block for each precondition. In order to ease that I have authored a very simple preCondition instruction for Jasmine 2.0's way of async testing: https://github.com/tiagorg/jasmine-precondition and also on NPM.

However for this case here, if we are able to use requireJS outside of the test we won't need to go down on this path. That would be cleaner I suppose

**Comment by joseph-jja** [comment]
Are you using jasmine 2.0 or 2.1?

**Comment by tiagorg** [comment]
2.1, just noticed the title saying 2.0. We are using the latest to see how would it be like.

**Comment by tiagorg** [comment]
unified karma's and main's require-config here: https://github.com/brendajin/marionette-ref-impl/commit/f27b750fb89c28133616d9d1ff5a911ccffebac6

**Comment by tiagorg** [comment]
Improving the specs for application: https://github.com/brendajin/marionette-ref-impl/commit/a411becc890edc0b2bc7b75f5085756b71c57ae7
