### ISSUE TITLE
Convert StringUtil and Globals tests to Jasmine 2.0

### ISSUE THREAD

**Issue by brendajin** [brendajin/marionette-ref-impl#9]

**Comment by tiagorg** [comment]
Right now I am integrating them with the new implementation

**Comment by tiagorg** [comment]
Done:
https://github.com/brendajin/marionette-ref-impl/commit/b7402ded29a14229b34858cae8414b67c5ff6029
https://github.com/brendajin/marionette-ref-impl/commit/b13c80798d7091e194c5ad184647b17ee0a1f75c
https://github.com/brendajin/marionette-ref-impl/commit/f9795ea1a88746dddba6a831ba9ba29b3523d24a
